# Generated by Django 6.0.3 on 2026-03-25 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='bin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
